version: "3.8"

services:
  postgres_db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - schnupperaufgabe_worksync_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"] # <-- Use variables here
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: on-failure
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@postgres_db:5432/${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      SUPERUSER_EMAIL: ${SUPERUSER_EMAIL}
      SUPERUSER_PASS: ${SUPERUSER_PASS}
    ports:
      - "3000:3000"
    depends_on:
      postgres_db:
        condition: service_healthy

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_started

volumes:
  schnupperaufgabe_worksync_postgres_data:
